# Generated by Django 5.2.8 on 2025-11-08 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(db_column='Id_Products', primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=150)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock', models.IntegerField(default=0)),
                ('Fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
