# Generated by Django 5.2.8 on 2025-11-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
