# Generated by Django 4.2.26 on 2025-11-08 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Fecha_Caducidad',
            field=models.DateField(db_column='Fecha_Caducidad', default='2025-12-31'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
