# Generated by Django 4.2.26 on 2025-11-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_producto_fecha_caducidad_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Telefono',
            field=models.CharField(max_length=20),
        ),
    ]
