# Generated by Django 4.2.26 on 2025-11-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(db_column='Id_Notificacion', primary_key=True, serialize=False)),
                ('Id_User', models.IntegerField()),
                ('Titulo', models.CharField(max_length=200)),
                ('Mensaje', models.TextField()),
                ('Tipo', models.CharField(max_length=50)),
                ('Id_Factura', models.IntegerField(blank=True, null=True)),
                ('Leida', models.BooleanField(default=False)),
                ('Fecha_Creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Notificaciones',
                'ordering': ['-Fecha_Creacion'],
            },
        ),
    ]
